FROM golang:1.7.3 AS builder
WORKDIR /go/src/github.com/gcpaladino/desafio-docker-go/ 
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /go/src/github.com/gcpaladino/desafio-docker-go/main .
CMD ["./main"]  
